// #define K_ENTER_LOGIN "Enter login id:\n"
// #define K_ENTER_PWD "Enter password:\n"
// #define K_ENTER_NAME "Enter name:\n"
// #define K_ENTER_AGE "Enter age:\n"
// #define K_ENTER_GENDER "Enter gender(M/F/O):\n"
// #define K_ENTER_ACC_NO "Enter account no.:\n"
// #define K_ENTER_CUST_ID "Enter customer id.:\n"
// #define K_ENTER_AMT "Enter amount:\n"
// #define K_ENTER_OLD_PWD "Enter old password:\n"
// #define K_ENTER_NEW_PWD "Enter new password:\n"

// #define K_CHANGE_NAME "Do you want to change your name?(Y/N)\n"
// #define K_CHANGE_AGE "Do you want to change your age?(Y/N)\n"
// #define K_CHANGE_GENDER "Do you want to change your gender?(Y/N)\n"
// #define K_CONFIRM "Do you confirm to make the above changes?(Y/N)\n"
// #define K_CONFIRM_NEW_PWD "Confirm new password:\n"

// #define K_USER_PAGE "\n\nUSER HOME PAGE\n\nPlease select \n1. Deposit \n2. Withdraw \n3. Balance enquiry \n4. Password change \n5. View details \n6. Logout\n"
// #define K_ADMIN_PAGE "\n\nADMIN HOME PAGE\n\nPlease select \n1. Get transaction details \n2. Get all bank account details \n3. Create new customer account \n4. Delete customer account \n5. Modify Account \n6. Get Customer details \n7. Logout\n"
// #define K_ACC_TYPE "Enter \n1. Single Account \n2. Joint Account\n"
// #define K_USER_TYPE "Enter \n1. ADMIN \n2. Customer \n3. Exit\n"

// #define K_ERROR_PWD_NOT_MATCHING "Passwords not matching!\n"
// #define K_ERROR_INCORRECT_PWD "Incorrect password!\n"
// #define K_INVALID_AMT "Entered Invalid Amount!\n"
// #define K_PWD_UPDATED "Password udpated!\n"
// #define K_INCORRECT_OPT "Please enter correct option!"
// #define K_EXIT "THANK YOU!"
// #define K_DUMMY "dummy"

#define mess "USER LOGIN\n1. Admin\n2. Student\n3. Professor\nEnter your choice: "
#define LOGIN_SUCCESS "Login successfull\n"
//#define PASSWORD "Enter your password: \n"
#define INVALID_PASSWORD "Password is invalid\n"
#define INVALID_LOGIN "Login id is invalid\n"

#define ADMIN_MENU "Admin Menu\n1. Add Student\n2. View Student Details\n3. Modify Student Details\n4. Deactivate Student\n5. Activate Student\n6. Add Faculty\6. Logout and Exit\nEnter your Choice: "
#define ADMIN_PASSWORD "root"
#define DEFAULT_PASSWORD "default"

#define ASK_CREDENTIALS "Enter your credentials to enter the portal.\n"
#define ASK_LOGIN "Enter your login id: "
#define ASK_PASSWORD "Enter your password: "
#define ASK_NAME "Enter your name: "
#define ASK_ID "Enter student id: "
#define LOGOUT_MSG "You have been logged out.\n"
#define ASK_AGE "Enter your age"
#define ASK_EMAIL "Enter your email"
#define ASK_ADDRESS "Enter your address"

#define ASK_COURSE_ID "Enter course id: "
#define ASK_COURSE_NAME "Enter course name: "
#define ASK_COURSE_CREDIT "Enter course credit: "
#define ASK_NEW_PASSWORD "Enter new password: "

#define ADMIN_LOGIN_ID "admin"